name: font_icon_to_flutter
version: 0.0.1
description: "Translate your CSS Font Icon to Dart for your Flutter Project."
repository:

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.6.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.13
  very_good_analysis: ^7.0.0
