name: font_icon_to_flutter
version: 0.1.1
description: "Translate your CSS Font Icon to Dart for your Flutter Project."
repository: https://github.com/vmichalak/font_icon_to_flutter
issue_tracker: https://github.com/vmichalak/font_icon_to_flutter/issues

topics:
  - cli
  - font
  - icon

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  font_icon_to_flutter:

dependencies:
  args: ^2.6.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
