import 'package:font_icon_to_flutter/src/model/icon_mapping.dart';
import 'package:font_icon_to_flutter/src/parser/iconly_io_icon_parser.dart';
import 'package:test/expect.dart';
import 'package:test/scaffolding.dart';

void main() {
  final parser = IconlyIoIconParser();

  group('IconlyIoIconParser().parse()', () {
    test('parse an empty input', () {
      expect(parser.parse(''), const Iterable<IconMapping>.empty());
    });

    test('parse an invalid input', () {
      const input = '''
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium 
          maximus nulla at convallis. Mauris rutrum ex vel lacus interdum 
          pulvinar. In efficitur euismod condimentum. Aenean id augue blandit, 
          scelerisque ex ut, tincidunt dolor. Cras venenatis lacus quam, eu 
          maximus erat dapibus eget. Fusce et lacinia magna. Nulla consequat 
          nisl et augue vestibulum commodo. Vestibulum ac libero vitae ipsum 
          mattis consequat. Morbi at lacus facilisis, rhoncus est quis, 
          efficitur lacus. Nam eget posuere eros. Aenean vehicula dignissim 
          ligula sit amet finibus. Sed nec egestas ex, varius pulvinar sem. 
          Curabitur fermentum tortor eleifend luctus cursus. Cras efficitur 
          vulputate tellus, et volutpat ipsum sodales at.''';
      expect(parser.parse(input), const Iterable<IconMapping>.empty());
    });

    test('parse a valid input', () {
      const input = r'''
          /*!
           *  Iconly icon font. Generated by Iconly: https://iconly.io/
           */
          
          @font-face {
            font-display: auto;
            font-family: "Iconly";
            font-style: normal;
            font-weight: 400;
            src: url("./iconly.eot?1734639429398");
            src: url("./iconly.eot?#iefix") format("embedded-opentype"), url("./iconly.woff2?1734639429398") format("woff2"), url("./iconly.woff?1734639429398") format("woff"), url("./iconly.ttf?1734639429398") format("truetype"), url("./iconly.svg?1734639429398#Iconly") format("svg");
          }
          
          [class="icon"], [class^="icon-"], [class*=" icon-"] {
            display: inline-block;
            font-family: "Iconly" !important;
            font-weight: 400;
            font-style: normal;
            font-variant: normal;
            text-rendering: auto;
            line-height: 1;
            -moz-osx-font-smoothing: grayscale;
            -webkit-font-smoothing: antialiased;
          }
          
          .icon-instagram:before {
            content: "\e000";
          }''';
      final output = parser.parse(input);
      const expected = IconMapping(key: 'instagram', codePoint: 'e000');
      expect(output.length, 1);
      expect(output.first, expected);
    });
  });
}
